version: 2
updates:
  # GitHub Actions - updates uses: statements in workflows
  - package-ecosystem: "github-actions"
    directory: "/" # Where your .github/workflows/ folder is
    schedule:
      interval: "monthly"

  # Gradle - updates dependencies in build.gradle or build.gradle.kts
  - package-ecosystem: "gradle"
    directory: "/" # Adjust if build.gradle is in a subfolder
    schedule:
      interval: "monthly"
