/**
 * [BoxLang]
 *
 * Copyright [2023] [Ortus Solutions, Corp]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ortus.boxlang.runtime.application;

import ortus.boxlang.runtime.context.ClassBoxContext;
import ortus.boxlang.runtime.context.IBoxContext;
import ortus.boxlang.runtime.context.RequestBoxContext;
import ortus.boxlang.runtime.dynamic.casters.BooleanCaster;
import ortus.boxlang.runtime.dynamic.casters.StringCaster;
import ortus.boxlang.runtime.runnables.IClassRunnable;
import ortus.boxlang.runtime.scopes.Key;
import ortus.boxlang.runtime.types.Function;
import ortus.boxlang.runtime.types.exceptions.AbortException;
import ortus.boxlang.runtime.types.util.BLCollector;
import ortus.boxlang.runtime.util.EncryptionUtil;

/**
 * I represent an Application listener that wraps an Application class instance, delegting to it, where possible and providing default
 * implementations otherwise
 */
public class ApplicationClassListener extends BaseApplicationListener {

	/**
	 * Application.bx listener for this request
	 */
	private IClassRunnable listener = null;

	/**
	 * Constructor
	 *
	 * @param listener An Application class instance
	 * @param context  The context to use
	 */
	public ApplicationClassListener( IClassRunnable listener, RequestBoxContext context ) {
		super( context );
		this.listener = listener;

		// Copy all the settings from the Application class to the settings map
		this.settings
		    .putAll( listener.getThisScope().entrySet().stream().filter( e -> ! ( e.getValue() instanceof Function ) ).collect( BLCollector.toStruct() ) );
		this.settings.put( Key.source, listener.getRunnablePath().absolutePath().toString() );
		this.settings.put( Key._CLASS, listener.getRunnablePath().absolutePath().toString() );

		// If there is no application name or if it's empty, make one up.
		String appName = StringCaster.cast( this.settings.get( Key._NAME ) );
		if ( appName == null || appName.isBlank() ) {
			this.settings.put( Key._NAME, "Autogenerated_Application_Name_" + EncryptionUtil.hash( listener.getRunnablePath().absolutePath().toString() ) );
		}
	}

	/**
	 * --------------------------------------------------------------------------
	 * Life-cycle methods
	 * --------------------------------------------------------------------------
	 */

	@Override
	public void onRequest( IBoxContext context, Object[] args ) {
		super.onRequest( context, args );

		if ( listener.getVariablesScope().containsKey( Key.onRequest ) ) {
			listener.dereferenceAndInvoke( context, Key.onRequest, args, false );
		} else {
			// Default includes template inside the Class's context
			ClassBoxContext cbc = new ClassBoxContext( context, listener );
			try {
				cbc.includeTemplate( ( String ) args[ 0 ] );
				cbc.flushBuffer( false );
			} catch ( AbortException e ) {
				cbc.flushBuffer( true );
				throw e;
			} catch ( Throwable e ) {
				cbc.flushBuffer( true );
				throw e;
			} finally {
				cbc.flushBuffer( true );
			}
		}
	}

	@Override
	public boolean onRequestStart( IBoxContext context, Object[] args ) {
		super.onRequestStart( context, args );

		if ( listener.getVariablesScope().containsKey( Key.onRequestStart ) ) {
			Object result = listener.dereferenceAndInvoke( context, Key.onRequestStart, args, false );
			if ( result != null ) {
				return BooleanCaster.cast( result );
			}
			// Null or no return value means true
			return true;
		}
		// Default implementation if there is no Application.bx or it has no onRequestStart method.
		return true;
	}

	@Override
	public void onSessionStart( IBoxContext context, Object[] args ) {
		super.onSessionStart( context, args );

		if ( listener.getVariablesScope().containsKey( Key.onSessionStart ) ) {
			listener.dereferenceAndInvoke( context, Key.onSessionStart, args, false );
		}
	}

	@Override
	public void onApplicationStart( IBoxContext context, Object[] args ) {
		super.onApplicationStart( context, args );

		if ( listener.getVariablesScope().containsKey( Key.onApplicationStart ) ) {
			listener.dereferenceAndInvoke( context, Key.onApplicationStart, args, false );
		}
	}

	@Override
	public void onRequestEnd( IBoxContext context, Object[] args ) {
		super.onRequestEnd( context, args );

		if ( listener.getVariablesScope().containsKey( Key.onRequestEnd ) ) {
			listener.dereferenceAndInvoke( context, Key.onRequestEnd, args, false );
		}
	}

	@Override
	public void onAbort( IBoxContext context, Object[] args ) {
		super.onAbort( context, args );

		if ( listener.getVariablesScope().containsKey( Key.onAbort ) ) {
			listener.dereferenceAndInvoke( context, Key.onAbort, args, false );
		}
	}

	@Override
	public void onSessionEnd( IBoxContext context, Object[] args ) {
		super.onSessionEnd( context, args );

		if ( listener.getVariablesScope().containsKey( Key.onSessionEnd ) ) {
			listener.dereferenceAndInvoke( context, Key.onSessionEnd, args, false );
		}
	}

	@Override
	public void onApplicationEnd( IBoxContext context, Object[] args ) {
		super.onApplicationEnd( context, args );

		if ( listener.getVariablesScope().containsKey( Key.onApplicationEnd ) ) {
			listener.dereferenceAndInvoke( context, Key.onApplicationEnd, args, false );
		}
	}

	@Override
	public boolean onError( IBoxContext context, Object[] args ) {
		super.onError( context, args );

		if ( listener.getVariablesScope().containsKey( Key.onError ) ) {
			listener.dereferenceAndInvoke( context, Key.onError, args, false );
			return true;
		} else {
			return false;
		}
	}

	@Override
	public boolean onMissingTemplate( IBoxContext context, Object[] args ) {
		super.onMissingTemplate( context, args );

		if ( listener.getVariablesScope().containsKey( Key.onMissingTemplate ) ) {
			Object result = listener.dereferenceAndInvoke( context, Key.onMissingTemplate, args, false );
			if ( result != null ) {
				return BooleanCaster.cast( result );
			}
			// Null or no return value means false
			return false;
		}
		// Default implementation if there is no Application.bx or it has no onMissingTemplate method.
		return false;
	}

	@Override
	public boolean onClassRequest( IBoxContext context, Object[] args ) {
		super.onClassRequest( context, args );
		return true;
	}

}
