/**
 * [BoxLang]
 *
 * Copyright [2023] [Ortus Solutions, Corp]
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the
 * License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS"
 * BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
package ortus.boxlang.runtime.jdbc.qoq;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import ortus.boxlang.compiler.ast.sql.select.SQLSelectStatement;
import ortus.boxlang.runtime.context.IBoxContext;

public class QoQPreparedStatement extends QoQStatement implements java.sql.PreparedStatement {

	private List<ParamItem>	parameters	= new ArrayList<ParamItem>();
	private String			sql;
	private int				autoGeneratedKeys;

	/**
	 * Constructor.
	 * 
	 * @param context    The BoxLang context.
	 * @param connection The connection.
	 */
	public QoQPreparedStatement( IBoxContext context, Connection connection, String sql, int autoGeneratedKeys ) {
		super( context, connection );
		this.sql				= sql;
		this.autoGeneratedKeys	= autoGeneratedKeys;
	}

	@Override
	public ResultSet executeQuery() throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'executeQuery'" );
	}

	@Override
	public int executeUpdate() throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'executeUpdate'" );
	}

	@Override
	public void setNull( int parameterIndex, int sqlType ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setNull'" );
	}

	@Override
	public void setBoolean( int parameterIndex, boolean x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setBoolean'" );
	}

	@Override
	public void setByte( int parameterIndex, byte x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setByte'" );
	}

	@Override
	public void setShort( int parameterIndex, short x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setShort'" );
	}

	@Override
	public void setInt( int parameterIndex, int x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setInt'" );
	}

	@Override
	public void setLong( int parameterIndex, long x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setLong'" );
	}

	@Override
	public void setFloat( int parameterIndex, float x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setFloat'" );
	}

	@Override
	public void setDouble( int parameterIndex, double x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setDouble'" );
	}

	@Override
	public void setBigDecimal( int parameterIndex, BigDecimal x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setBigDecimal'" );
	}

	@Override
	public void setString( int parameterIndex, String x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setString'" );
	}

	@Override
	public void setBytes( int parameterIndex, byte[] x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setBytes'" );
	}

	@Override
	public void setDate( int parameterIndex, Date x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setDate'" );
	}

	@Override
	public void setTime( int parameterIndex, Time x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setTime'" );
	}

	@Override
	public void setTimestamp( int parameterIndex, Timestamp x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setTimestamp'" );
	}

	@Override
	public void setAsciiStream( int parameterIndex, InputStream x, int length ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setAsciiStream'" );
	}

	@Override
	public void setUnicodeStream( int parameterIndex, InputStream x, int length ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setUnicodeStream'" );
	}

	@Override
	public void setBinaryStream( int parameterIndex, InputStream x, int length ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setBinaryStream'" );
	}

	@Override
	public void clearParameters() throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'clearParameters'" );
	}

	@Override
	public void setObject( int parameterIndex, Object x, int targetSqlType ) throws SQLException {
		// index is 1 based!

		var item = new ParamItem( parameterIndex, x, targetSqlType );
		if ( parameters.size() < parameterIndex ) {
			// add nulls if there are missing slots
			// I assume this never happens
			while ( parameters.size() < parameterIndex - 1 ) {
				parameters.add( null );
			}
			parameters.add( item );
		} else {
			parameters.set( parameterIndex - 1, item );
		}

	}

	/**
	 * Get the parameters
	 */
	public List<ParamItem> getParameters() {
		return parameters;
	}

	@Override
	public void setObject( int parameterIndex, Object x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setObject'" );
	}

	@Override
	public boolean execute() throws SQLException {
		// parse the SQL string into an AST object
		SQLSelectStatement select = ( SQLSelectStatement ) QoQExecutionService.parseSQL( sql );

		// execute the query
		result = QoQExecutionService.executeSelect( context, select, this );
		return true;
	}

	@Override
	public void addBatch() throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'addBatch'" );
	}

	@Override
	public void setCharacterStream( int parameterIndex, Reader reader, int length ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setCharacterStream'" );
	}

	@Override
	public void setRef( int parameterIndex, Ref x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setRef'" );
	}

	@Override
	public void setBlob( int parameterIndex, Blob x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setBlob'" );
	}

	@Override
	public void setClob( int parameterIndex, Clob x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setClob'" );
	}

	@Override
	public void setArray( int parameterIndex, Array x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setArray'" );
	}

	@Override
	public ResultSetMetaData getMetaData() throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'getMetaData'" );
	}

	@Override
	public void setDate( int parameterIndex, Date x, Calendar cal ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setDate'" );
	}

	@Override
	public void setTime( int parameterIndex, Time x, Calendar cal ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setTime'" );
	}

	@Override
	public void setTimestamp( int parameterIndex, Timestamp x, Calendar cal ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setTimestamp'" );
	}

	@Override
	public void setNull( int parameterIndex, int sqlType, String typeName ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setNull'" );
	}

	@Override
	public void setURL( int parameterIndex, URL x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setURL'" );
	}

	@Override
	public ParameterMetaData getParameterMetaData() throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'getParameterMetaData'" );
	}

	@Override
	public void setRowId( int parameterIndex, RowId x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setRowId'" );
	}

	@Override
	public void setNString( int parameterIndex, String value ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setNString'" );
	}

	@Override
	public void setNCharacterStream( int parameterIndex, Reader value, long length ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setNCharacterStream'" );
	}

	@Override
	public void setNClob( int parameterIndex, NClob value ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setNClob'" );
	}

	@Override
	public void setClob( int parameterIndex, Reader reader, long length ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setClob'" );
	}

	@Override
	public void setBlob( int parameterIndex, InputStream inputStream, long length ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setBlob'" );
	}

	@Override
	public void setNClob( int parameterIndex, Reader reader, long length ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setNClob'" );
	}

	@Override
	public void setSQLXML( int parameterIndex, SQLXML xmlObject ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setSQLXML'" );
	}

	@Override
	public void setObject( int parameterIndex, Object x, int targetSqlType, int scaleOrLength ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setObject'" );
	}

	@Override
	public void setAsciiStream( int parameterIndex, InputStream x, long length ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setAsciiStream'" );
	}

	@Override
	public void setBinaryStream( int parameterIndex, InputStream x, long length ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setBinaryStream'" );
	}

	@Override
	public void setCharacterStream( int parameterIndex, Reader reader, long length ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setCharacterStream'" );
	}

	@Override
	public void setAsciiStream( int parameterIndex, InputStream x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setAsciiStream'" );
	}

	@Override
	public void setBinaryStream( int parameterIndex, InputStream x ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setBinaryStream'" );
	}

	@Override
	public void setCharacterStream( int parameterIndex, Reader reader ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setCharacterStream'" );
	}

	@Override
	public void setNCharacterStream( int parameterIndex, Reader value ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setNCharacterStream'" );
	}

	@Override
	public void setClob( int parameterIndex, Reader reader ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setClob'" );
	}

	@Override
	public void setBlob( int parameterIndex, InputStream inputStream ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setBlob'" );
	}

	@Override
	public void setNClob( int parameterIndex, Reader reader ) throws SQLException {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException( "Unimplemented method 'setNClob'" );
	}

	public record ParamItem( int index, Object value, int type ) {
	}
}
