/**
 * [BoxLang]
 *
 * Copyright [2023] [Ortus Solutions, Corp]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ortus.boxlang.runtime.types;

import java.util.List;

import ortus.boxlang.compiler.ast.statement.BoxMethodDeclarationModifier;
import ortus.boxlang.compiler.parser.BoxSourceType;
import ortus.boxlang.runtime.context.FunctionBoxContext;
import ortus.boxlang.runtime.loader.ImportDefinition;
import ortus.boxlang.runtime.scopes.Key;
import ortus.boxlang.runtime.util.ResolvedFilePath;

/**
 * A compiled BoxLang Function that comes from compiled source code.
 * This class extends Function and provides concrete implementations
 * for UDF, Closure, and Lambda classes that are generated by the compiler.
 */
public abstract class CompiledFunction extends Function {

	/**
	 * The enclosing class of the function, if any
	 */
	private Class<?>														enclosingClass	= null;

	/**
	 * --------------------------------------------------------------------------
	 * Properties
	 * --------------------------------------------------------------------------
	 */

	private final List<BoxMethodDeclarationModifier>						modifiers;
	private final Key														name;
	private final Argument[]												arguments;
	private final String													returnType;
	private final Function.Access											access;
	private final IStruct													annotations;
	private final IStruct													documentation;
	private final List<ImportDefinition>									imports;
	private final BoxSourceType												sourceType;
	private final ResolvedFilePath											runnablePath;
	private final java.util.function.Function<FunctionBoxContext, Object>	invoker;

	/**
	 * --------------------------------------------------------------------------
	 * Constructors
	 * --------------------------------------------------------------------------
	 */

	/**
	 * Simple constructor for subclasses that override all getters.
	 * Sets all fields to null/empty defaults.
	 */
	protected CompiledFunction() {
		super();
		this.name			= null;
		this.arguments		= null;
		this.returnType		= null;
		this.access			= null;
		this.annotations	= null;
		this.documentation	= null;
		this.modifiers		= null;
		this.imports		= null;
		this.sourceType		= null;
		this.runnablePath	= null;
		this.invoker		= null;
	}

	/**
	 * Constructor
	 *
	 * @param name          The name of the function
	 * @param arguments     The arguments of the function
	 * @param returnType    The return type of the function
	 * @param access        The access modifier of the function
	 * @param annotations   The annotations of the function
	 * @param documentation The documentation of the function
	 * @param modifiers     The modifiers of the function
	 * @param defaultOutput Whether the function should output by default
	 * @param imports       The imports for this function
	 * @param sourceType    The source type of the function
	 * @param runnablePath  The path to the runnable
	 * @param invoker       The functional interface to invoke the function logic
	 */
	protected CompiledFunction(
	    Key name,
	    Argument[] arguments,
	    String returnType,
	    Function.Access access,
	    IStruct annotations,
	    IStruct documentation,
	    List<BoxMethodDeclarationModifier> modifiers,
	    boolean defaultOutput,
	    List<ImportDefinition> imports,
	    BoxSourceType sourceType,
	    ResolvedFilePath runnablePath,
	    java.util.function.Function<FunctionBoxContext, Object> invoker ) {

		super( defaultOutput );
		this.name			= name;
		this.arguments		= arguments;
		this.returnType		= returnType;
		this.access			= access;
		this.annotations	= annotations;
		this.documentation	= documentation;
		this.modifiers		= modifiers;
		this.imports		= imports;
		this.sourceType		= sourceType;
		this.runnablePath	= runnablePath;
		this.invoker		= invoker;
	}

	/**
	 * --------------------------------------------------------------------------
	 * Abstract method implementations from Function
	 * --------------------------------------------------------------------------
	 */

	/**
	 * Get the name of the function.
	 *
	 * @return function name
	 */
	@Override
	public Key getName() {
		return this.name;
	}

	/**
	 * Get the arguments of the function.
	 *
	 * @return array of arguments
	 */
	@Override
	public Argument[] getArguments() {
		return this.arguments;
	}

	/**
	 * Get the return type of the function.
	 *
	 * @return return type
	 */
	@Override
	public String getReturnType() {
		return this.returnType;
	}

	/**
	 * Get any annotations declared for this function, both the @annotation syntax and inline.
	 *
	 * @return function metadata
	 */
	@Override
	public IStruct getAnnotations() {
		return this.annotations;
	}

	/**
	 * Get the contents of the documentation comment for this function.
	 *
	 * @return function metadata
	 */
	@Override
	public IStruct getDocumentation() {
		return this.documentation;
	}

	/**
	 * Get access modifier of the function
	 *
	 * @return function access modifier
	 */
	@Override
	public Access getAccess() {
		return this.access;
	}

	/**
	 * Get the imports for this function.
	 *
	 * @return list of import definitions
	 */
	@Override
	public List<ImportDefinition> getImports() {
		return this.imports;
	}

	/**
	 * Get the source type of the function.
	 *
	 * @return the source type
	 */
	@Override
	public BoxSourceType getSourceType() {
		return this.sourceType;
	}

	/**
	 * Get the path to the runnable.
	 *
	 * @return the resolved file path
	 */
	@Override
	public ResolvedFilePath getRunnablePath() {
		return this.runnablePath;
	}

	/**
	 * Get modifier of the function
	 *
	 * @return function modifiers
	 */
	@Override
	public List<BoxMethodDeclarationModifier> getModifiers() {
		return this.modifiers;
	}

	/**
	 * Invoke the actual function logic
	 *
	 * @param context The function box context
	 *
	 * @return The result of the function invocation
	 */
	@Override
	public Object _invoke( FunctionBoxContext context ) {
		return this.invoker.apply( context );
	}

	/**
	 * Get the enclosing class of the function, if any.
	 * Lazy loads it
	 */
	public Class<?> getEnclosingClass() {
		if ( enclosingClass == null ) {
			synchronized ( this.getClass() ) {
				if ( enclosingClass == null ) {
					enclosingClass = this.invoker != null ? this.invoker.getClass() : this.getClass();
				}
			}
		}
		return enclosingClass;
	}

}
