# If BoxLang Core builds then this workflow will kick off the runtime builds
# for: web-support
name: Trigger Runtime Builds

on:
  workflow_run:
    workflows: [Snapshots]
    types: [completed]
    branches:
      - "development"
  # Allow manual triggering
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        repo:
          - "ortus-boxlang/boxlang-web-support"

    steps:
      - name: Trigger Build Workflow for ${{ matrix.repo }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHA_WORKFLOW_DISPATCHER_PAT_BOXLANG }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ matrix.repo }}/actions/workflows/snapshot.yml/dispatches \
            -d '{"ref": "development"}'
